command_timeout = 1000

[aws]
disabled = true


[git_commit]
commit_hash_length = 7
only_detached = false
style = "bold yellow"
# format = '[\($hash$tag\)]($style) '
tag_disabled = false
tag_symbol = "🔖 "
